### ISSUE TITLE
Consider integrating this feature upstream?

### ISSUE THREAD

**Issue by adamcik** [HeadspringLabs/mopidy-qsaver#3]
Hi,

We (as in mopidy) have https://github.com/mopidy/mopidy/issues/310 open which nobody has had time to implement just yet. You seem to be on track to solving at least part of that bug and we would love if this could also make it upstream :-)

-Thomas

**Comment by bardoloi** [comment]
Thomas,

That will be interesting. Should we run with user @jodal's list of requirements in [this comment](https://github.com/mopidy/mopidy/issues/310#issuecomment-89789143) as the final requirements?

-Vishal

**Comment by adamcik** [comment]
That looks correct, and we would be happy even if the initial version starts with just tracklist support to match what this extension is solving.
